version: '3.8'

services:
  sim_stack:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: earthen_uav_sim
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ..:/workspace/Autonomous-Drone-Inspection
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
